/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.muratkuk.nesneproje;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FilenameFilter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muratkuk
 */
public class ParentFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form ParentFrame
     */
    private ExerciseManager exerciseManager;
    private DefaultTableModel model;
    private DefaultComboBoxModel<String> comboBoxModel;
    private DefaultListModel<String> csvFileListModel;
    private String[] csvFiles;
    public ParentFrame(ExerciseManager exerciseManager) {
        this.setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e) {
                ParentFrame.this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
                ParentFrame.this.setVisible(false);
                ParentFrame.this.dispose();
                new LoginFrame(new UserCredentials()).setVisible(true);
                
            }
        });
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.exerciseManager = exerciseManager;
        comboBoxModel = new DefaultComboBoxModel<>();
        for (String username : UserCredentials.getChildUsernames()) {
            comboBoxModel.addElement(username);
        }
        csvFileListModel = new DefaultListModel<>();
        initComponents();
        if (usernameComboBox.getItemCount() > 0) {
            usernameComboBox.setSelectedIndex(0);
        }
        loadExercises();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        aSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        nSpinner = new javax.swing.JSpinner();
        createButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usernameComboBox = new javax.swing.JComboBox<>(comboBoxModel);
        jScrollPane1 = new javax.swing.JScrollPane();
        csvFileList = new javax.swing.JList<>(csvFileListModel);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        parentChart1 = new com.muratkuk.nesneproje.ParentChart();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parent");

        jLabel1.setText("Parent");

        aSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel2.setText("First Number Limit");

        jLabel3.setText("Second Number Limit");

        bSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel4.setText("Number of Questions");

        nSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        createButton.setText("Create Exercise");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "First Limit", "Second Limit", "Number of Questions"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel5.setText("Exercise Name");

        usernameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameComboBoxActionPerformed(evt);
            }
        });

        csvFileList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        csvFileList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csvFileListMouseClicked(evt);
            }
        });
        csvFileList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                csvFileListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(csvFileList);

        jLabel6.setText("Exercises");

        jLabel7.setText("Exercise Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(bSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(aSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(createButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jLabel6)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usernameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(95, 95, 95)))
                .addGap(30, 30, 30)
                .addComponent(parentChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parentChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addGap(5, 5, 5)
                            .addComponent(aSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(createButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(usernameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadExercises() {
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        List<Exercise> exercises = exerciseManager.loadExercises();
        for (Exercise exercise : exercises) {
            model.addRow(new Object[]{exercise.getName(), exercise.getA(), exercise.getB(), exercise.getN()});
        }
    }   
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String name = nameField.getText();
        int a = (Integer) aSpinner.getValue();
        int b = (Integer) bSpinner.getValue();
        int N = (Integer) nSpinner.getValue();
        exerciseManager.createAndSaveExercise(name, a, b, N);
        loadExercises();
    }//GEN-LAST:event_createButtonActionPerformed

    private void usernameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameComboBoxActionPerformed
        String selectedUsername = (String) usernameComboBox.getSelectedItem();
        updateCSVFiles(selectedUsername);        // TODO add your handling code here:
    }//GEN-LAST:event_usernameComboBoxActionPerformed

    private void csvFileListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_csvFileListValueChanged
        /*if (!evt.getValueIsAdjusting()) {
            String selectedFile = csvFileList.getSelectedValue();
            new CSVViewerFrame(selectedFile).setVisible(true);
        }*/            // TODO add your handling code here:
    }//GEN-LAST:event_csvFileListValueChanged

    private void csvFileListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csvFileListMouseClicked
        if (evt.getClickCount() == 2) {
            int index = csvFileList.locationToIndex(evt.getPoint());
            //String selectedFile = csvFileListModel.getElementAt(index);
            String selectedFile = csvFiles[index];
            new CSVViewerFrame(selectedFile).setVisible(true);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_csvFileListMouseClicked


    private String[] getCSVFiles(String username) {
        File folder = new File(System.getProperty("user.dir"));
        File[] listOfFiles = folder.listFiles();
        List<String> csvFiles = new ArrayList<>();

        for (File file : listOfFiles) {
            if (file.isFile() && file.getName().startsWith(username) && file.getName().endsWith(".csv")) {
                csvFiles.add(file.getName());
            }
        }

        return csvFiles.toArray(new String[csvFiles.size()]);
    }
    private void updateCSVFiles(String username) {
        csvFiles = getCSVFiles(username);

        csvFileListModel.clear();
        for (String csvFile : csvFiles) {
            String[] csvsp = csvFile.split("_");
            String[] asd = csvsp[3].split(".csv");
            csvFileListModel.addElement(csvsp[0]+" | "+csvsp[1]+" | "+csvsp[2]+" | "+asd[0]);
        }
    }    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner aSpinner;
    private javax.swing.JSpinner bSpinner;
    private javax.swing.JButton createButton;
    private javax.swing.JList<String> csvFileList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner nSpinner;
    private javax.swing.JTextField nameField;
    private com.muratkuk.nesneproje.ParentChart parentChart1;
    private javax.swing.JComboBox<String> usernameComboBox;
    // End of variables declaration//GEN-END:variables
}
